# Generated by Django 4.0.2 on 2022-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
