# Generated by Django 4.0.2 on 2022-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='drame', max_length=100),
        ),
    ]
